package cmd

import "fmt"

const (
	AppName    = "DOCX关键词替换工具"
	AppVersion = "1.0.0"
)

// ShowUsage 显示使用帮助
func ShowUsage() {
	fmt.Printf("%s v%s\n\n", AppName, AppVersion)
	fmt.Println("用法:")
	fmt.Println("  docx-replacer [选项]")
	fmt.Println()
	fmt.Println("选项:")
	fmt.Println("  -config string")
	fmt.Println("        配置文件路径 (默认 \"config.json\")")
	fmt.Println("  -input string")
	fmt.Println("        输入 DOCX 文件路径")
	fmt.Println("  -output string")
	fmt.Println("        输出 DOCX 文件路径")
	fmt.Println("  -input-dir string")
	fmt.Println("        输入目录路径（批量处理）")
	fmt.Println("  -output-dir string")
	fmt.Println("        输出目录路径（批量处理）")
	fmt.Println("  -verbose")
	fmt.Println("        详细输出")
	fmt.Println("  -version")
	fmt.Println("        显示版本信息")
	fmt.Println("  -help")
	fmt.Println("        显示帮助信息")
	fmt.Println()
	fmt.Println("示例:")
	fmt.Println("  # 处理单个文件")
	fmt.Println("  docx-replacer -config config.json -input input.docx -output output.docx")
	fmt.Println()
	fmt.Println("  # 批量处理目录中的所有文件")
	fmt.Println("  docx-replacer -config config.json -input-dir ./input -output-dir ./output")
	fmt.Println()
	fmt.Println("配置文件格式 (JSON):")
	fmt.Println(`  {`)
	fmt.Println(`    "project_name": "项目名称",`)
	fmt.Println(`    "keywords": [`)
	fmt.Println(`      {`)
	fmt.Println(`        "key": "NAME",`)
	fmt.Println(`        "value": "张三"`)
	fmt.Println(`      },`)
	fmt.Println(`      {`)
	fmt.Println(`        "key": "AGE",`)
	fmt.Println(`        "value": "25"`)
	fmt.Println(`      }`)
	fmt.Println(`    ]`)
	fmt.Println(`  }`)
	fmt.Println()
	fmt.Println("注意事项:")
	fmt.Println("  - 在 DOCX 文档中，关键词需要使用 #KEY# 格式")
	fmt.Println("  - 支持普通文本和表格中的关键词替换")
	fmt.Println("  - 自动处理表格中被 XML 标签分割的关键词")
	fmt.Println("  - 如果未指定输出文件/目录，将自动生成")
}